### ISSUE TITLE
Crash in file diff view between 2 changesets

### ISSUE THREAD

**Issue by ntmlod** [trac-hacks/trac-UserPicturesPlugin#4]
Hello,

I installed this plugin recently (last revision 36), no problem with the different views (timeline, ticket or default changeset). But a user reported an issue on the very specific case of comparing 2 changesets of a given file. Here is the log:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/trac/web/main.py", line 497, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.7/site-packages/trac/web/main.py", line 233, in dispatch
    content_type)
  File "/usr/lib/python2.7/site-packages/trac/web/chrome.py", line 983, in render_template
    stream |= self._filter_stream(req, method, filename, stream, data)
  File "/usr/lib64/python2.7/site-packages/genshi/core.py", line 132, in __or__
    return Stream(_ensure(function(self)), serializer=self.serializer)
  File "/usr/lib/python2.7/site-packages/trac/web/chrome.py", line 1162, in inner
    data)
  File "build/bdist.linux-x86_64/egg/userpictures/__init__.py", line 82, in filter_stream
    filter_.extend(self._browser_filter(req, data))
  File "build/bdist.linux-x86_64/egg/userpictures/__init__.py", line 188, in _browser_filter
    filter_.extend(self._browser_changeset_filter(req, data))
  File "build/bdist.linux-x86_64/egg/userpictures/__init__.py", line 197, in _browser_changeset_filter
    author = data['changeset'].author
AttributeError: 'bool' object has no attribute 'author'
```

My first guess is that where in a situation that has not been planned by the conditional loop:

```
    def _browser_changeset_filter(self, req, data):
        author = None
        if (data.get('file') or {}).get('changeset'):
            author = data['file']['changeset'].author
        elif 'changeset' in data:
            author = data['changeset'].author
        if author is None:
            return []
```

In particular, it is a changeset but in the default mode view (without UP plugin) no author information is published so probably not loaded (based on my little but growing knowledge of Trac).

**Comment by ejucovy** [comment]
Hm - I'm having trouble reproducing this.  I'll keep looking, but:
- can you give me a sample url?  I'm looking at a URL like https://mytracsite.com/changeset?reponame=foo&new=c93a08583b8899349299c4af3344c59f56db789f%40foo&old=d3f54fa7e1c828654f8b2ab71c8b43ce943d5d01%40foo -- is that the right place to look for this bug?
- what release or changeset of trac itself are you running?

**Comment by ntmlod** [comment]
We are running the current stable release (1.0) but I have a different pattern in the URL (perhaps we are not talking about the same view):

https://mytracsite.com/changeset?old=XXXX&old_path=/my/old/path&new=XXXX&new_path=/my/new/path

**Comment by ejucovy** [comment]
I just pushed a commit that should fix this - could you try it out?  (I'll make a new release once this is confirmed to work -- I'm still having trouble reproducing the bug for some reason.)

**Comment by ntmlod** [comment]
Perfect, no more issue on the file diff view between 2 revisions.
